// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uepla;

namespace Uepla.Migrations
{
    [DbContext(typeof(FormContext))]
    [Migration("20190520063150_OrnekTipi_diger")]
    partial class OrnekTipi_diger
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Uepla.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklamalar");

                    b.Property<int?>("AmdRehberi");

                    b.Property<int?>("Antibiyotik");

                    b.Property<int?>("Cinsiyet");

                    b.Property<int?>("Mikroorganizma");

                    b.Property<int?>("OrnekTipi");

                    b.Property<int?>("ProtokolNumarasi");

                    b.Property<int?>("SirDurumu");

                    b.Property<DateTime?>("SonucCikisTarihi");

                    b.Property<int?>("TestUygulandiMi");

                    b.Property<int?>("Tur");

                    b.Property<int?>("Yas");

                    b.Property<int?>("Yontem");

                    b.Property<int?>("ZoneCapi");

                    b.HasKey("Id");

                    b.ToTable("MyForm");
                });
#pragma warning restore 612, 618
        }
    }
}
